import streamlit as st
import streamlit.components.v1 as components
import textwrap
from services.optimizer import optimize_prompt
from services.analyzer import PromptAnalyzer
from services.scoring import PromptScoringEngine

from services.scoring import (
    PromptScoringEngine,
    calculate_local_score,
)

from services.database import (
    init_database,
    save_prompt,
    get_prompt_history,
    delete_prompt,
)


def calculate_improvement(original_score, optimized_score):
    """
    Calculate the difference between the original
    and optimized prompt scores.
    """

    improvement = optimized_score - original_score

    return improvement


def copy_to_clipboard(text):
    """
    Create a browser-based copy-to-clipboard button.
    """

    escaped_text = (
        text
        .replace("\\", "\\\\")
        .replace("`", "\\`")
        .replace("${", "\\${")
    )

    components.html(
        f"""
        <script>
            function copyPrompt() {{

                const text = `{escaped_text}`;

                navigator.clipboard.writeText(text);

                const button =
                    document.getElementById("copy-button");

                button.innerText = "✓ Copied!";

                setTimeout(() => {{
                    button.innerText = "📋 Copy Prompt";
                }}, 2000);
            }}
        </script>

        <button
            id="copy-button"
            onclick="copyPrompt()"
            style="
                width: 100%;
                padding: 10px 18px;
                border-radius: 8px;
                border: 1px solid #475569;
                background: #1e293b;
                color: white;
                cursor: pointer;
                font-size: 14px;
                font-weight: 600;
            "
        >
            📋 Copy Prompt
        </button>
        """,
        height=55,
    )


def create_report(
    original_prompt,
    optimized_prompt,
    score_breakdown,
    optimized_score,
    improvement,
):
    """
    Generate a downloadable text report.
    """

    report = f"""
PROMPT OPTIMIZER STUDIO
=======================

PROMPT ANALYSIS REPORT


ORIGINAL PROMPT
---------------

{original_prompt}


SCORE BREAKDOWN
---------------

Final Score: {score_breakdown["final_score"]}/100

Clarity: {score_breakdown["clarity"]}/100

Context: {score_breakdown["context"]}/100

Specificity: {score_breakdown["specificity"]}/100

Constraints: {score_breakdown["constraints"]}/100

Output Format: {score_breakdown["output_format"]}/100

Examples: {score_breakdown["examples"]}/100


PROMPT IMPROVEMENT
------------------

Original Score: {score_breakdown["final_score"]}/100

Optimized Score: {optimized_score}/100

Improvement: {improvement:+d} points


OPTIMIZED PROMPT
----------------

{optimized_prompt}


Generated by Prompt Optimizer Studio
"""

    return report

# ============================================================
# INITIALIZE DATABASE
# ============================================================

init_database()


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Prompt Optimizer Studio",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="collapsed",
)


# ============================================================
# SESSION STATE
# ============================================================

if "result" not in st.session_state:
    st.session_state.result = None

if "local_analysis" not in st.session_state:
    st.session_state.local_analysis = None

if "score_breakdown" not in st.session_state:
    st.session_state.score_breakdown = None

if "optimized_score" not in st.session_state:
    st.session_state.optimized_score = None

if "improvement" not in st.session_state:
    st.session_state.improvement = None

if "page" not in st.session_state:
    st.session_state.page = "Optimizer"


# ============================================================
# CUSTOM CSS
# ============================================================
st.markdown(
    """
    <style>

    /* =====================================================
       GLOBAL
       ===================================================== */

    .stApp {
        background:
            radial-gradient(
                circle at top left,
                rgba(59, 130, 246, 0.10),
                transparent 35%
            ),
            radial-gradient(
                circle at top right,
                rgba(139, 92, 246, 0.08),
                transparent 30%
            ),
            #0b1120;
        color: #f8fafc;
    }


    .block-container {
        max-width: 1180px;
        padding-top: 2rem;
        padding-bottom: 5rem;
    }


    /* =====================================================
       HIDE STREAMLIT DEFAULT ELEMENTS
       ===================================================== */

    #MainMenu {
        visibility: hidden;
    }

    footer {
        visibility: hidden;
    }

    header {
        visibility: hidden;
    }


    /* =====================================================
       TYPOGRAPHY
       ===================================================== */

    .hero-title {
        font-size: 48px;
        font-weight: 800;
        line-height: 1.1;
        letter-spacing: -1.5px;
        color: #f8fafc;
        margin-bottom: 12px;
    }


    .hero-gradient {
        background:
            linear-gradient(
                90deg,
                #60a5fa,
                #a78bfa
            );

        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }


    .hero-subtitle {
        font-size: 18px;
        line-height: 1.6;
        color: #94a3b8;
        max-width: 700px;
        margin-bottom: 35px;
    }


    .section-title {
        font-size: 22px;
        font-weight: 700;
        color: #f8fafc;
        margin-top: 30px;
        margin-bottom: 15px;
    }


    /* =====================================================
       TOP BRAND
       ===================================================== */

    .brand {
        display: flex;
        align-items: center;
        gap: 12px;
        margin-bottom: 35px;
    }


    .brand-icon {
        width: 42px;
        height: 42px;
        border-radius: 12px;

        display: flex;
        align-items: center;
        justify-content: center;

        background:
            linear-gradient(
                135deg,
                #3b82f6,
                #8b5cf6
            );

        font-size: 21px;
    }


    .brand-name {
        font-size: 19px;
        font-weight: 700;
        color: #f8fafc;
    }


    .brand-subtitle {
        font-size: 12px;
        color: #64748b;
    }


    /* =====================================================
       CARDS
       ===================================================== */

    .glass-card {
        background: rgba(15, 23, 42, 0.72);
        border: 1px solid rgba(148, 163, 184, 0.12);
        border-radius: 18px;
        padding: 24px;
        backdrop-filter: blur(12px);
        box-shadow:
            0 10px 35px rgba(0, 0, 0, 0.18);
    }


    .score-card {
        background: rgba(15, 23, 42, 0.72);
        border: 1px solid rgba(148, 163, 184, 0.12);
        border-radius: 16px;
        padding: 20px;
        min-height: 115px;
    }


    /* =====================================================
       METRICS
       ===================================================== */

    [data-testid="stMetric"] {
        background: rgba(15, 23, 42, 0.72);
        border: 1px solid rgba(148, 163, 184, 0.12);
        padding: 18px;
        border-radius: 16px;
    }


    [data-testid="stMetricLabel"] {
        color: #94a3b8 !important;
    }


    [data-testid="stMetricValue"] {
        color: #f8fafc !important;
        font-weight: 750;
    }


    /* =====================================================
       TEXT AREA
       ===================================================== */

    textarea {
        background-color: #111827 !important;
        color: #f8fafc !important;
        border: 1px solid #263244 !important;
        border-radius: 14px !important;
    }


    textarea:focus {
        border: 1px solid #6366f1 !important;
        box-shadow:
            0 0 0 1px #6366f1 !important;
    }


    /* =====================================================
       BUTTONS
       ===================================================== */

    .stButton > button {
        min-height: 46px;
        border-radius: 11px;
        border: 1px solid #334155;
        font-weight: 650;
        transition: all 0.2s ease;
    }


    .stButton > button:hover {
        border-color: #6366f1;
        transform: translateY(-1px);
    }


    /* Primary button */

    .stButton > button[kind="primary"] {
        background:
            linear-gradient(
                135deg,
                #2563eb,
                #7c3aed
            );

        border: none;

        color: white;

        box-shadow:
            0 8px 25px rgba(79, 70, 229, 0.25);
    }


    .stButton > button[kind="primary"]:hover {
        box-shadow:
            0 12px 35px rgba(79, 70, 229, 0.35);
    }


    /* =====================================================
       DOWNLOAD BUTTON
       ===================================================== */

    .stDownloadButton > button {
        width: 100%;
        min-height: 45px;

        border-radius: 11px;

        background: #1E293B;

        border: 1px solid #334155;

        color:#E2E8F0;

        font-weight: 600;
    }


    .stDownloadButton > button:hover {
        border-color: #6366f1;
    }


    /* =====================================================
       TABS
       ===================================================== */

    button[data-baseweb="tab"] {
        color: #94a3b8;
        font-weight: 600;
    }


    button[data-baseweb="tab"][aria-selected="true"] {
        color: #a78bfa;
    }


    /* =====================================================
       PROGRESS BAR
       ===================================================== */

    [data-testid="stProgressBar"] {
        margin-bottom: 12px;
    }


    /* =====================================================
       SIDEBAR
       ===================================================== */

    section[data-testid="stSidebar"] {
        background: #0f172a;
        border-right: 1px solid #1e293b;
    }


    section[data-testid="stSidebar"] h2 {
        color: #f8fafc;
    }

    section[data-testid="stSidebar"] {
        background: #0b1220;
        border-right: 1px solid #1e293b;
    }


    section[data-testid="stSidebar"] > div {
        padding-top: 2rem;
    }


    .sidebar-brand {
        display: flex;
        align-items: center;
        gap: 10px;
        margin-bottom: 25px;
    }


    .sidebar-logo {
        width: 34px;
        height: 34px;
        border-radius: 10px;

        display: flex;
        align-items: center;
        justify-content: center;

        background: linear-gradient(
            135deg,
            #2563eb,
            #7c3aed
        );

        color: white;
        font-size: 18px;
    }


    .sidebar-title {
        color: #f8fafc;
        font-size: 16px;
        font-weight: 700;
    }


    .sidebar-heading {
        color: #f8fafc;
        font-size: 14px;
        font-weight: 700;
        margin-bottom: 12px;
    }


    .sidebar-description {
        color: #94a3b8;
        font-size: 12px;
        line-height: 1.7;
    }


    .sidebar-powered {
        color: #64748b;
        font-size: 11px;
        margin-top: 20px;
    }


    /* =====================================================
       DIVIDER
       ===================================================== */

    hr {
        border-color: #1e293b !important;
    }


    /* =====================================================
       SUCCESS / WARNING / INFO
       ===================================================== */

    [data-testid="stAlert"] {
        border-radius: 12px;
    }


    </style>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# NAVBAR
# ============================================================

st.markdown(
    """
    <div style="
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 15px 20px;
        background: rgba(15, 23, 42, 0.72);
        border-bottom: 1px solid rgba(148, 163, 184, 0.12);
        border-radius: 0 0 12px 12px;
        margin-bottom: 25px;
    ">
        <div style="display: flex; align-items: center; gap: 12px;">
            <div style="
                width: 40px;
                height: 40px;
                border-radius: 10px;
                display: flex;
                align-items: center;
                justify-content: center;
                background: linear-gradient(135deg, #3b82f6, #8b5cf6);
                font-size: 20px;
            ">✦</div>
            <div style="
                font-size: 18px;
                font-weight: 700;
                color: #f8fafc;
            ">Prompt Optimizer Studio</div>
        </div>
        <div style="font-size: 12px; color: #64748b;">
            AI Prompt Engineering Workspace
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)




col1, col2, col3 = st.columns(3)

with col1:
    
    if st.button("🤖 Optimizer", use_container_width=True):
        st.session_state.page = "Optimizer"

with col2:
    if st.button("📋 History", use_container_width=True):
        st.session_state.page = "History"

with col3:
    if st.button("ℹ️ About", use_container_width=True):
        st.session_state.page = "About"



page = st.session_state.page

# ============================================================
# OPTIMIZER PAGE
# ============================================================

if page == "Optimizer":

    # ========================================================
    # HEADER
    # ========================================================

    # st.markdown(
    # """
    # <div class="brand">
    #   <div class="brand-icon">🤖</div>
    #   <div class="brand-info">
    #     <div class="brand-name">Prompt Optimizer Studio</div>
    #     <div class="brand-subtitle">AI Prompt Engineering Workspace</div>
    #   </div>
    # </div>
    # """,
    # unsafe_allow_html=True,
    # )


    # st.markdown(
    #     textwrap.dedent("""
    #     <div class="hero-title">
    #         Transform Your Prompts
    #         <br>
    #         <span class="hero-gradient">
    #             Into Better AI Instructions
    #         </span>
    #     </div>
    #     """).strip(),
    #     unsafe_allow_html=True,
    # )


    # st.markdown(
    #     textwrap.dedent("""
    #     <div class="hero-subtitle">
    #         Analyze your prompt quality, identify missing
    #         information, and generate optimized prompt.
    #     </div>
    #     """).strip(),
    #     unsafe_allow_html=True,
    # )

    # ========================================================
    # PROMPT INPUT
    # ========================================================

    st.markdown(
            """
            <div class="section-title">
                ✦ Analyze your prompt quality, identify missing
            information, and generate optimized prompt.
            </div>
            """,
            unsafe_allow_html=True,
        )





    prompt = st.text_area(
        "Prompt",
        height=220,
        placeholder=(
             "Write your prompt here..."
           
        ),
        label_visibility="collapsed",
    )

    # st.markdown(
    #     """
    #     <div style="
    #         display:flex;
    #         gap:10px;
    #         flex-wrap:wrap;
    #         margin-top:10px;
    #         margin-bottom:20px;
    #     ">

    #     <span style="
    #         background:#111827;
    #         border:1px solid #263244;
    #         padding:7px 12px;
    #         border-radius:20px;
    #         color:#94a3b8;
    #         font-size:13px;
    #     ">
    #         ✦ AI Analysis
    #     </span>

    #     <span style="
    #         background:#111827;
    #         border:1px solid #263244;
    #         padding:7px 12px;
    #         border-radius:20px;
    #         color:#94a3b8;
    #         font-size:13px;
    #     ">
    #         ✦ Smart Scoring
    #     </span>

    #     <span style="
    #         background:#111827;
    #         border:1px solid #263244;
    #         padding:7px 12px;
    #         border-radius:20px;
    #         color:#94a3b8;
    #         font-size:13px;
    #     ">
    #         ✦ Prompt Variations
    #     </span>

    #     <span style="
    #         background:#111827;
    #         border:1px solid #263244;
    #         padding:7px 12px;
    #         border-radius:20px;
    #         color:#94a3b8;
    #             ont-size:13px;
    #     ">
    #         ✦ History
    #     </span>

    #     </div>
    #     """,
    #     unsafe_allow_html=True,
    # )

    # ========================================================
    # OPTIMIZE BUTTON
    # ========================================================

    optimize_clicked = st.button(
        "✨ Optimize Prompt",
        type="primary",
        use_container_width=True,
    )
    


    


    # ========================================================
    # PROCESS PROMPT
    # ========================================================

    if optimize_clicked:

        if not prompt.strip():

            st.warning(
                "Please enter a prompt first."
            )

        else:

            with st.spinner(
                "Analyzing and optimizing your prompt..."
            ):

                try:

                    # ----------------------------------------
                    # LOCAL PYTHON ANALYSIS
                    # ----------------------------------------

                    analyzer = PromptAnalyzer(prompt)

                    local_analysis = analyzer.analyze()


                    # ----------------------------------------
                    # GEMINI ANALYSIS
                    # ----------------------------------------
                    
                    result = optimize_prompt(prompt)

                    # ------------------------------------------------
                    # ANALYZE OPTIMIZED PROMPT
                    # ------------------------------------------------

                    optimized_analyzer = PromptAnalyzer(
                        result.optimized_prompt
                    )

                    optimized_local_analysis = (
                        optimized_analyzer.analyze()
                    )

                    # ----------------------------------------
                    # OPTIMIZED SCORE
                    # ----------------------------------------


                    optimized_score = calculate_local_score(
                        optimized_local_analysis
                        )

                    
                    # ----------------------------------------
                    # HYBRID SCORING ENGINE
                    # ----------------------------------------

                    scoring_engine = PromptScoringEngine(
                        local_analysis=local_analysis,
                        gemini_result=result,
                    )

                    score_breakdown = (
                        scoring_engine.get_breakdown()
                    )


                    # ----------------------------------------
                    # ORIGINAL SCORE
                    # ----------------------------------------

                    original_score = score_breakdown["final_score"]

                    # ----------------------------------------
                    # CALCULATE IMPROVEMENT
                    # ----------------------------------------
                    improvement = calculate_improvement(
                        original_score,
                        optimized_score,
                    )

                    # ----------------------------------------
                    # SAVE RESULTS
                    # ----------------------------------------

                    st.session_state.result = result

                    st.session_state.local_analysis = (
                        local_analysis
                    )

                    st.session_state.score_breakdown = (
                        score_breakdown
                    )

                    st.session_state.optimized_score = optimized_score

                    st.session_state.improvement = improvement
                    # ========================================================
                    # SAVE TO DATABASE
                    # ========================================================

                    save_prompt(
                        original_prompt=prompt,
                        final_score=score_breakdown["final_score"],
                        clarity=score_breakdown["clarity"],
                        context=score_breakdown["context"],
                        specificity=score_breakdown["specificity"],
                        optimized_prompt=result.optimized_prompt,
                    )


                except RuntimeError as error:

                    # Gemini/API errors are shown as a clean user message.
                    st.error(
                        f"⚠️ {error}"
                    )

                except ValueError as error:

                    # Validation/JSON errors from the AI response.
                    st.error(
                        f"⚠️ The AI returned an unexpected response: {error}"
                    )

                except Exception as error:

                    # Prevent the Streamlit app from crashing while keeping
                    # the actual error visible during development.
                    st.error(
                        f"⚠️ Something went wrong: {error}"
                    )


    st.divider()


    # ========================================================
    # LOAD SESSION RESULTS
    # ========================================================

    # Always read results from session state after the processing block.
    # This prevents the UI from depending on a local `result` variable
    # that may not exist when an API/analysis error occurs.
    result = st.session_state.get("result")

    local_analysis = st.session_state.get("local_analysis")

    score_breakdown = st.session_state.get("score_breakdown")


    # ========================================================
    # DISPLAY VALUES
    # ========================================================

    if (
        result
        and local_analysis
        and score_breakdown
    ):

        # Hybrid final score
        score = score_breakdown["final_score"]

        # Local Python analysis
        word_count = local_analysis["word_count"]

        sentence_count = local_analysis["sentence_count"]

        # Hybrid/Gemini scores
        clarity = score_breakdown["clarity"]

        specificity = score_breakdown["specificity"]

    else:

        score = "--"

        word_count = "--"

        sentence_count = "--"

        clarity = "--"

        specificity = "--"


    # ========================================================
    # PROMPT ANALYSIS
    # ========================================================

    st.markdown(
    """
    <div class="section-title">
        📊 Prompt Intelligence
    </div>
    """,
    unsafe_allow_html=True,
)


    # --------------------------------------------------------
    # METRIC CARDS
    # --------------------------------------------------------

    col1, col2, col3, col4 = st.columns(4)


    with col1:

        st.metric(
            label="Prompt Score",
            value=score,
        )


    with col2:

        st.metric(
            label="Word Count",
            value=word_count,
        )


    with col3:

        st.metric(
            label="Clarity",
            value=clarity,
        )


    with col4:

        st.metric(
            label="Specificity",
            value=specificity,
        )


    # ========================================================
    # SCORE BREAKDOWN
    # ========================================================

    if score_breakdown:

        st.markdown(
            '<div class="section-title">Score Breakdown</div>',
            unsafe_allow_html=True,
        )


        st.progress(
            score_breakdown["clarity"] / 100,
            text=(
                f"Clarity — "
                f"{score_breakdown['clarity']}/100"
            ),
        )


        st.progress(
            score_breakdown["context"] / 100,
            text=(
                f"Context — "
                f"{score_breakdown['context']}/100"
            ),
        )


        st.progress(
            score_breakdown["specificity"] / 100,
            text=(
                f"Specificity — "
                f"{score_breakdown['specificity']}/100"
            ),
        )


        st.progress(
            score_breakdown["constraints"] / 100,
            text=(
                f"Constraints — "
                f"{score_breakdown['constraints']}/100"
            ),
        )


        st.progress(
            score_breakdown["output_format"] / 100,
            text=(
                f"Output Format — "
                f"{score_breakdown['output_format']}/100"
            ),
        )


        st.progress(
            score_breakdown["examples"] / 100,
            text=(
                f"Examples — "
                f"{score_breakdown['examples']}/100"
            ),
        )

    # ========================================================
    # PROMPT IMPROVEMENT
    # ========================================================

    if (
        score_breakdown
        and st.session_state.optimized_score is not None
    ):

        st.markdown(
            '<div class="section-title">📈 Prompt Improvement</div>',
            unsafe_allow_html=True,

                # """
                # <div class="section-title">
                #     📈 Prompt Improvement
                # </div>
                # """
        )

        original_score = score_breakdown["final_score"]

        optimized_score = (
            st.session_state.optimized_score
        )

        improvement = (
            st.session_state.improvement
        )


        col1, col2, col3 = st.columns(3)


        with col1:

            st.metric(
                label="Original Score",
                value=f"{original_score}/100",
            )


        with col2:

            st.metric(
                label="Optimized Score",
                value=f"{optimized_score}/100",
            )


        with col3:

            if improvement > 0:

                st.metric(
                    label="Improvement",
                    value=f"+{improvement}",
                )

            elif improvement < 0:

                st.metric(
                    label="Improvement",
                    value=str(improvement),
                )

            else:

                st.metric(
                    label="Improvement",
                    value="0",
                )
        # ----------------------------------------------------
        # STEP 11 — VISUAL IMPROVEMENT MESSAGE
        # ----------------------------------------------------

        if improvement > 0:

            st.success(
                f"Your prompt improved by {improvement} points."
            )

        elif improvement == 0:

            st.info(
                "The optimized prompt has the same "
                "deterministic score."
            )

        else:

            st.warning(
                f"The optimized prompt scored "
                f"{abs(improvement)} points lower."
            )
    # ========================================================
    # PROMPT STRUCTURE
    # ========================================================

    if local_analysis:

        st.markdown(
            '<div class="section-title">Prompt Structure</div>',
            unsafe_allow_html=True,
        )


        col1, col2, col3 = st.columns(3)


        # ----------------------------------------------------
        # COLUMN 1
        # ----------------------------------------------------

        with col1:

            if local_analysis["has_role"]:

                st.success(
                    "✓ Role detected"
                )

            else:

                st.warning(
                    "✗ No role detected"
                )


            if local_analysis["has_context"]:

                st.success(
                    "✓ Context detected"
                )

            else:

                st.warning(
                    "✗ No context detected"
                )


        # ----------------------------------------------------
        # COLUMN 2
        # ----------------------------------------------------

        with col2:

            if local_analysis["has_constraints"]:

                st.success(
                    "✓ Constraints detected"
                )

            else:

                st.warning(
                    "✗ No constraints detected"
                )


            if local_analysis["has_output_format"]:

                st.success(
                    "✓ Output format detected"
                )

            else:

                st.warning(
                    "✗ No output format detected"
                )


        # ----------------------------------------------------
        # COLUMN 3
        # ----------------------------------------------------

        with col3:

            if local_analysis["has_examples"]:

                st.success(
                    "✓ Examples detected"
                )

            else:

                st.warning(
                    "✗ No examples detected"
                )


            st.info(
                f"Sentences: {sentence_count}"
            )


    # ========================================================
    # MISSING INFORMATION
    # ========================================================

    st.markdown(
        '<div class="section-title">Missing Information</div>',
        unsafe_allow_html=True,
    )


    if result:

        if result.missing_items:

            for item in result.missing_items:

                st.write(
                    f"• {item}"
                )

        else:

            st.success(
                "Your prompt contains the important "
                "information needed."
            )

    else:

        st.info(
            "Your prompt analysis will appear here "
            "after optimization."
        )


    # ========================================================
    # OPTIMIZED PROMPT
    # ========================================================

    if result:

        st.markdown(
            '<div class="section-title">Optimized Prompt</div>',
            unsafe_allow_html=True,
        )


        st.text_area(
            "Optimized Prompt",
            value=result.optimized_prompt,
            height=250,
            label_visibility="collapsed",
        )

    # ----------------------------------------------------
    # COPY
    # ----------------------------------------------------
        copy_to_clipboard(
                result.optimized_prompt
            )

    # ----------------------------------------------------
    # DOWNLOAD PROMPT
    # ----------------------------------------------------

        st.download_button(
            label="📥 Download Prompt",
            data=result.optimized_prompt,
            file_name="optimized_prompt.txt",
            mime="text/plain",
            use_container_width=True,
        )

    # ----------------------------------------------------
    # CREATE REPORT
    # ----------------------------------------------------

        report = create_report(
        original_prompt=prompt,
        optimized_prompt=result.optimized_prompt,
        score_breakdown=score_breakdown,
        optimized_score=st.session_state.optimized_score,
        improvement=st.session_state.improvement,
    )



    # ----------------------------------------------------
    # DOWNLOAD REPORT
    # ----------------------------------------------------


        st.download_button(
        label="📊 Download Analysis Report",
        data=report,
        file_name="prompt_analysis_report.txt",
        mime="text/plain",
        use_container_width=True,
    )

    # ========================================================
    # PROMPT VARIATIONS
    # ========================================================

    st.markdown(
        '<div class="section-title">Prompt Variations</div>',
        unsafe_allow_html=True,
    )


    tab1, tab2, tab3, tab4, tab5 = st.tabs(
        [
            "Standard",
            "Developer",
            "System",
            "Few-shot",
            "JSON",
        ]
    )


    # ========================================================
    # STANDARD PROMPT
    # ========================================================

    with tab1:

        if result:

            st.text_area(
                "Standard Prompt",
                value=result.standard,
                height=220,
            )

        else:

            st.info(
                "Optimize a prompt to see the standard version."
            )


    # ========================================================
    # DEVELOPER PROMPT
    # ========================================================

    with tab2:

        if result:

            st.text_area(
                "Developer Prompt",
                value=result.developer,
                height=220,
            )

        else:

            st.info(
                "Optimize a prompt to see the developer version."
            )


    # ========================================================
    # SYSTEM PROMPT
    # ========================================================

    with tab3:

        if result:

            st.text_area(
                "System Prompt",
                value=result.system,
                height=220,
            )

        else:

            st.info(
                "Optimize a prompt to see the system version."
            )


    # ========================================================
    # FEW-SHOT PROMPT
    # ========================================================

    with tab4:

        if result:

            st.text_area(
                "Few-shot Prompt",
                value=result.few_shot,
                height=220,
            )

        else:

            st.info(
                "Optimize a prompt to see the few-shot version."
            )


    # ========================================================
    # JSON PROMPT
    # ========================================================

    with tab5:

        if result:

            st.text_area(
                "JSON Prompt",
                value=result.json_mode,
                height=220,
            )

        else:

            st.info(
                "Optimize a prompt to see the JSON version."
            )


# ============================================================
# HISTORY PAGE
# ============================================================

# ============================================================
# HISTORY PAGE
# ============================================================

elif page == "History":

    st.markdown(
        '<div class="main-title" style=" color: #A5B4FC; font-weight: 600;">Prompt History</div>',
        unsafe_allow_html=True,
    )

    # st.markdown(
    #     """
    #     <div class="subtitle">
    #         Review your previously optimized prompts.
    #     </div>
    #     """,
    #     unsafe_allow_html=True,
    # )


    # --------------------------------------------------------
    # GET HISTORY
    # --------------------------------------------------------

    history = get_prompt_history()


    # --------------------------------------------------------
    # EMPTY STATE
    # --------------------------------------------------------

    if not history:

        st.info(
            """
            No prompt history yet.

            Go to the Optimizer and optimize your
            first prompt.
            """
        )


    # --------------------------------------------------------
    # HISTORY LIST
    # --------------------------------------------------------

    else:

        # st.write(
        #     f"**{len(history)} prompts optimized**"
        # )

        # st.divider()


        for row in history:

            prompt_id = row["id"]

            original_prompt = row["original_prompt"]

            final_score = row["final_score"]

            clarity = row["clarity"]

            context = row["context"]

            specificity = row["specificity"]

            optimized_prompt = row["optimized_prompt"]

            created_at = row["created_at"]


            # ------------------------------------------------
            # EXPANDER
            # ------------------------------------------------

            with st.expander(
                f"#{prompt_id} — Score: {final_score}/100 — {created_at}"
            ):

                st.markdown("### Original Prompt")

                st.code(
                    original_prompt,
                    language="text",
                )


                # --------------------------------------------
                # METRICS
                # --------------------------------------------

                col1, col2, col3, col4 = st.columns(4)


                with col1:

                    st.metric(
                        "Final Score",
                        final_score,
                    )


                with col2:

                    st.metric(
                        "Clarity",
                        clarity,
                    )


                with col3:

                    st.metric(
                        "Context",
                        context,
                    )


                with col4:

                    st.metric(
                        "Specificity",
                        specificity,
                    )


                # --------------------------------------------
                # OPTIMIZED PROMPT
                # --------------------------------------------

                st.markdown(
                    "### Optimized Prompt"
                )

                st.text_area(
                    "Optimized Prompt",
                    value=optimized_prompt,
                    height=200,
                    key=f"history_prompt_{prompt_id}",
                )


                # --------------------------------------------
                # DELETE BUTTON
                # --------------------------------------------

                if st.button(
                    "🗑️ Delete",
                    key=f"delete_{prompt_id}",
                ):

                    delete_prompt(prompt_id)

                    st.success(
                        "Prompt deleted."
                    )

                    st.rerun()
# ============================================================
# ABOUT PAGE
# ============================================================

elif page == "About":

    # ========================================================
    # ABOUT HEADER
    # ========================================================

    st.markdown(
        """
        <div class="hero-title">
            About
            <br>
            <span class="hero-gradient">
                Prompt Optimizer Studio
            </span>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown(
        """
        <div class="hero-subtitle">
            An AI-powered prompt engineering workspace designed
            to analyze, improve, and evaluate prompts before
            sending them to a language model.
        </div>
        """,
        unsafe_allow_html=True,
    )


    # ========================================================
    # OVERVIEW
    # ========================================================

    st.markdown("## ✦ What is Prompt Optimizer Studio?")

    st.write(
        """
        Prompt Optimizer Studio is an AI-powered developer tool
        that helps users understand, evaluate, and improve their
        prompts.

        Instead of simply sending a prompt directly to an AI model,
        the application analyzes the prompt structure, identifies
        missing information, evaluates prompt quality, and uses
        Gemini AI to generate an improved version.

        The project combines deterministic Python-based analysis
        with AI-powered optimization to create a more reliable
        prompt engineering workflow.
        """
    )


    # ========================================================
    # HOW IT WORKS
    # ========================================================

    st.markdown("## ⚙️ How It Works")

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        st.markdown("### 01")

        st.markdown("**Analyze**")

        st.caption(
            "Inspect prompt structure, clarity, "
            "context and specificity."
        )


    with col2:

        st.markdown("### 02")

        st.markdown("**Score**")

        st.caption(
            "Evaluate the prompt using a hybrid "
            "scoring system."
        )


    with col3:

        st.markdown("### 03")

        st.markdown("**Optimize**")

        st.caption(
            "Use Gemini AI to transform the prompt "
            "into a stronger version."
        )


    with col4:

        st.markdown("### 04")

        st.markdown("**Compare**")

        st.caption(
            "Compare original and optimized "
            "prompt quality."
        )


    # ========================================================
    # CURRENT FEATURES
    # ========================================================

    st.markdown("## 🚀 Current Features")

    features = [
        "Prompt quality scoring",
        "Hybrid scoring engine",
        "Clarity analysis",
        "Context analysis",
        "Specificity analysis",
        "Word and sentence analysis",
        "Role detection",
        "Constraint detection",
        "Output format detection",
        "Example detection",
        "Missing information detection",
        "AI-powered prompt optimization",
        "Multiple prompt optimization styles",
        "Original vs optimized score comparison",
        "Prompt improvement calculation",
        "Prompt history",
        "SQLite persistence",
        "Copy optimized prompts",
        "Download optimized prompts",
        "Download analysis reports",
    ]

    col1, col2 = st.columns(2)

    for index, feature in enumerate(features):

        with col1 if index % 2 == 0 else col2:

            st.markdown(
                f"✓ {feature}"
            )


    # ========================================================
    # TECHNOLOGY
    # ========================================================

    st.markdown("## 🛠️ Technology")

    technology_data = {
        "Technology": [
            "Python",
            "Streamlit",
            "Gemini API",
            "Pydantic",
            "SQLite",
            "Hybrid Scoring",
        ],

        "Purpose": [
            "Core application and analysis logic",
            "Interactive web application",
            "AI-powered prompt optimization",
            "Structured data validation",
            "Local prompt history persistence",
            "Combines deterministic analysis with AI",
        ],
    }

    st.table(technology_data)


    # ========================================================
    # PROJECT STATUS
    # ========================================================

    st.markdown("## 📌 Project Status")

    st.success("🟢 Active Development")

    st.write(
        """
        The core Prompt Optimizer Studio functionality is
        implemented. The project is currently being prepared for production
        deployment.
        """
    )


    # ========================================================
    # WHAT'S NEXT
    # ========================================================

    st.markdown("## 🔮 What's Next")

    upcoming = [
        "Production-ready error handling",
        "API key and secrets management",
        "Performance and UX improvements",
        "Responsive UI refinement",
        "Professional project documentation",
        "GitHub repository preparation",
        "Free cloud deployment",
    ]

    for item in upcoming:

        st.markdown(f"◦ {item}")


    # ========================================================
    # FOOTER
    # ========================================================

    st.divider()

    st.caption(
        "Prompt Optimizer Studio • "
        "Built with Python • Streamlit • Gemini AI"
    )

# ============================================================
# FOOTER
# ============================================================

st.markdown(
    """
    <div style="
        margin-top:70px;
        padding-top:25px;
        border-top:1px solid #1e293b;
        text-align:center;
        color:#64748b;
        font-size:13px;
    ">

        Prompt Optimizer Studio
        Built with Python • Streamlit • Gemini AI

    </div>
    """,
    unsafe_allow_html=True,
)